from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 670)
        MainWindow.setMinimumSize(QtCore.QSize(730, 670))
        MainWindow.setMaximumSize(QtCore.QSize(730, 670))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.load_img_btn = QtWidgets.QPushButton(self.groupBox)
        self.load_img_btn.setGeometry(QtCore.QRect(10, 40, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.load_img_btn.setFont(font)
        self.load_img_btn.setObjectName("load_img_btn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 10, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.default_conv_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.default_conv_rbtn.setGeometry(QtCore.QRect(10, 30, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.default_conv_rbtn.setFont(font)
        self.default_conv_rbtn.setObjectName("default_conv_rbtn")
        self.gray_conv_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.gray_conv_rbtn.setGeometry(QtCore.QRect(10, 50, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.gray_conv_rbtn.setFont(font)
        self.gray_conv_rbtn.setObjectName("gray_conv_rbtn")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 10, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.sp_noise_rbtn = QtWidgets.QRadioButton(self.groupBox_3)
        self.sp_noise_rbtn.setGeometry(QtCore.QRect(10, 20, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sp_noise_rbtn.setFont(font)
        self.sp_noise_rbtn.setObjectName("sp_noise_rbtn")
        self.gaussian_noise_rbtn = QtWidgets.QRadioButton(self.groupBox_3)
        self.gaussian_noise_rbtn.setGeometry(QtCore.QRect(10, 40, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.gaussian_noise_rbtn.setFont(font)
        self.gaussian_noise_rbtn.setObjectName("gaussian_noise_rbtn")
        self.poisson_noise_rbtn = QtWidgets.QRadioButton(self.groupBox_3)
        self.poisson_noise_rbtn.setGeometry(QtCore.QRect(10, 60, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.poisson_noise_rbtn.setFont(font)
        self.poisson_noise_rbtn.setObjectName("poisson_noise_rbtn")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 110, 431, 108))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.brightness_adj_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.brightness_adj_btn.setGeometry(QtCore.QRect(30, 28, 160, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.brightness_adj_btn.setFont(font)
        self.brightness_adj_btn.setObjectName("brightness_adj_btn")
        self.contrast_adj_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.contrast_adj_btn.setGeometry(QtCore.QRect(240, 28, 160, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.contrast_adj_btn.setFont(font)
        self.contrast_adj_btn.setObjectName("contrast_adj_btn")
        self.histogram_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.histogram_btn.setGeometry(QtCore.QRect(30, 68, 160, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.histogram_btn.setFont(font)
        self.histogram_btn.setObjectName("histogram_btn")
        self.histogram_equalizer_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.histogram_equalizer_btn.setGeometry(QtCore.QRect(240, 68, 160, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.histogram_equalizer_btn.setFont(font)
        self.histogram_equalizer_btn.setObjectName("histogram_equalizer_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 230, 431, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lpf_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.lpf_btn.setGeometry(QtCore.QRect(30, 50, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lpf_btn.setFont(font)
        self.lpf_btn.setObjectName("lpf_btn")
        self.hpf_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.hpf_btn.setGeometry(QtCore.QRect(30, 80, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.hpf_btn.setFont(font)
        self.hpf_btn.setObjectName("hpf_btn")
        self.medf_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.medf_btn.setGeometry(QtCore.QRect(30, 110, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.medf_btn.setFont(font)
        self.medf_btn.setObjectName("medf_btn")
        self.avgf_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.avgf_btn.setGeometry(QtCore.QRect(30, 140, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.avgf_btn.setFont(font)
        self.avgf_btn.setObjectName("avgf_btn")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(170, 20, 231, 161))
        self.groupBox_6.setObjectName("groupBox_6")
        self.laplacian_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.laplacian_edf_rbtn.setGeometry(QtCore.QRect(10, 30, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.laplacian_edf_rbtn.setFont(font)
        self.laplacian_edf_rbtn.setObjectName("laplacian_edf_rbtn")
        self.gaussian_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.gaussian_edf_rbtn.setGeometry(QtCore.QRect(10, 50, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.gaussian_edf_rbtn.setFont(font)
        self.gaussian_edf_rbtn.setObjectName("gaussian_edf_rbtn")
        self.vertsobel_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.vertsobel_edf_rbtn.setGeometry(QtCore.QRect(10, 70, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.vertsobel_edf_rbtn.setFont(font)
        self.vertsobel_edf_rbtn.setObjectName("vertsobel_edf_rbtn")
        self.horizprewitt_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.horizprewitt_edf_rbtn.setGeometry(QtCore.QRect(10, 130, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.horizprewitt_edf_rbtn.setFont(font)
        self.horizprewitt_edf_rbtn.setObjectName("horizprewitt_edf_rbtn")
        self.horizsobel_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.horizsobel_edf_rbtn.setGeometry(QtCore.QRect(10, 90, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.horizsobel_edf_rbtn.setFont(font)
        self.horizsobel_edf_rbtn.setObjectName("horizsobel_edf_rbtn")
        self.vertprewitt_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.vertprewitt_edf_rbtn.setGeometry(QtCore.QRect(10, 110, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.vertprewitt_edf_rbtn.setFont(font)
        self.vertprewitt_edf_rbtn.setObjectName("vertprewitt_edf_rbtn")
        self.log_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.log_edf_rbtn.setGeometry(QtCore.QRect(130, 50, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.log_edf_rbtn.setFont(font)
        self.log_edf_rbtn.setObjectName("log_edf_rbtn")
        self.zerocross_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.zerocross_edf_rbtn.setGeometry(QtCore.QRect(130, 90, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.zerocross_edf_rbtn.setFont(font)
        self.zerocross_edf_rbtn.setObjectName("zerocross_edf_rbtn")
        self.skeleton_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.skeleton_edf_rbtn.setGeometry(QtCore.QRect(130, 110, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.skeleton_edf_rbtn.setFont(font)
        self.skeleton_edf_rbtn.setObjectName("skeleton_edf_rbtn")
        self.canny_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.canny_edf_rbtn.setGeometry(QtCore.QRect(130, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.canny_edf_rbtn.setFont(font)
        self.canny_edf_rbtn.setObjectName("canny_edf_rbtn")
        self.prewitt_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.prewitt_edf_rbtn.setGeometry(QtCore.QRect(130, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.prewitt_edf_rbtn.setFont(font)
        self.prewitt_edf_rbtn.setObjectName("prewitt_edf_rbtn")
        self.sobel_edf_rbtn = QtWidgets.QRadioButton(self.groupBox_6)
        self.sobel_edf_rbtn.setGeometry(QtCore.QRect(130, 130, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sobel_edf_rbtn.setFont(font)
        self.sobel_edf_rbtn.setObjectName("sobel_edf_rbtn")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 430, 181, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.linedetect_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.linedetect_btn.setGeometry(QtCore.QRect(10, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.linedetect_btn.setFont(font)
        self.linedetect_btn.setObjectName("linedetect_btn")
        self.circledetect_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.circledetect_btn.setGeometry(QtCore.QRect(10, 90, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.circledetect_btn.setFont(font)
        self.circledetect_btn.setObjectName("circledetect_btn")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(210, 430, 241, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.dilation_morph_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.dilation_morph_btn.setGeometry(QtCore.QRect(50, 30, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dilation_morph_btn.setFont(font)
        self.dilation_morph_btn.setObjectName("dilation_morph_btn")
        self.close_morph_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.close_morph_btn.setGeometry(QtCore.QRect(50, 90, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.close_morph_btn.setFont(font)
        self.close_morph_btn.setObjectName("close_morph_btn")
        self.open_morph_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.open_morph_btn.setGeometry(QtCore.QRect(50, 120, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.open_morph_btn.setFont(font)
        self.open_morph_btn.setObjectName("open_morph_btn")
        self.erosion_morph_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.erosion_morph_btn.setGeometry(QtCore.QRect(50, 60, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.erosion_morph_btn.setFont(font)
        self.erosion_morph_btn.setObjectName("erosion_morph_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 330, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.save_img_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_img_btn.setGeometry(QtCore.QRect(60, 610, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_img_btn.setFont(font)
        self.save_img_btn.setObjectName("save_img_btn")
        self.exit_prog_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_prog_btn.setGeometry(QtCore.QRect(240, 610, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exit_prog_btn.setFont(font)
        self.exit_prog_btn.setObjectName("exit_prog_btn")
        self.orig_img_lbl = QtWidgets.QLabel(self.centralwidget)
        self.orig_img_lbl.setGeometry(QtCore.QRect(470, 90, 240, 240))
        self.orig_img_lbl.setAutoFillBackground(True)
        self.orig_img_lbl.setFrameShape(QtWidgets.QFrame.Box)
        self.orig_img_lbl.setText("")
        self.orig_img_lbl.setScaledContents(False)
        self.orig_img_lbl.setObjectName("orig_img_lbl")
        self.res_img_lbl = QtWidgets.QLabel(self.centralwidget)
        self.res_img_lbl.setGeometry(QtCore.QRect(470, 360, 240, 240))
        self.res_img_lbl.setAutoFillBackground(True)
        self.res_img_lbl.setFrameShape(QtWidgets.QFrame.Box)
        self.res_img_lbl.setText("")
        self.res_img_lbl.setScaledContents(False)
        self.res_img_lbl.setObjectName("res_img_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Load image"))
        self.load_img_btn.setText(_translate("MainWindow", "open"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Convert"))
        self.default_conv_rbtn.setText(_translate("MainWindow", "default color"))
        self.gray_conv_rbtn.setText(_translate("MainWindow", "gray color"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Add Noise"))
        self.sp_noise_rbtn.setText(_translate("MainWindow", "salt pepper"))
        self.gaussian_noise_rbtn.setText(_translate("MainWindow", "gaussian"))
        self.poisson_noise_rbtn.setText(_translate("MainWindow", "poisson"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Point Transform op\'s"))
        self.brightness_adj_btn.setText(_translate("MainWindow", "brightness adjustment"))
        self.contrast_adj_btn.setText(_translate("MainWindow", "Contrast adjustment"))
        self.histogram_btn.setText(_translate("MainWindow", "Histogram"))
        self.histogram_equalizer_btn.setText(_translate("MainWindow", "Histogram equalization"))
        self.label.setText(_translate("MainWindow", "Original image"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Local Transform op\'s"))
        self.lpf_btn.setText(_translate("MainWindow", "Low Pass filter"))
        self.hpf_btn.setText(_translate("MainWindow", "High Pass filter"))
        self.medf_btn.setText(_translate("MainWindow", "Median filter"))
        self.avgf_btn.setText(_translate("MainWindow", "Averaging"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Edge Detection filters"))
        self.laplacian_edf_rbtn.setText(_translate("MainWindow", "Laplacian filter"))
        self.gaussian_edf_rbtn.setText(_translate("MainWindow", "Gaussian filter"))
        self.vertsobel_edf_rbtn.setText(_translate("MainWindow", "Vert. sobel"))
        self.horizprewitt_edf_rbtn.setText(_translate("MainWindow", "horiz.prewitt"))
        self.horizsobel_edf_rbtn.setText(_translate("MainWindow", "horiz. sobel"))
        self.vertprewitt_edf_rbtn.setText(_translate("MainWindow", "vert. prewitt"))
        self.log_edf_rbtn.setText(_translate("MainWindow", "Log"))
        self.zerocross_edf_rbtn.setText(_translate("MainWindow", "Zero cross"))
        self.skeleton_edf_rbtn.setText(_translate("MainWindow", "skeleton"))
        self.canny_edf_rbtn.setText(_translate("MainWindow", "Canny method"))
        self.prewitt_edf_rbtn.setText(_translate("MainWindow", "Prewitt"))
        self.sobel_edf_rbtn.setText(_translate("MainWindow", "Sobel"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Global Transform op\'s"))
        self.linedetect_btn.setText(_translate("MainWindow", "Line detection using hough"))
        self.circledetect_btn.setText(_translate("MainWindow", "Circle detection using hough"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Morphological op\'s"))
        self.dilation_morph_btn.setText(_translate("MainWindow", "Dilation"))
        self.close_morph_btn.setText(_translate("MainWindow", "Close"))
        self.open_morph_btn.setText(_translate("MainWindow", "Open"))
        self.erosion_morph_btn.setText(_translate("MainWindow", "Erosion"))
        self.label_4.setText(_translate("MainWindow", "Result"))
        self.save_img_btn.setText(_translate("MainWindow", "save result"))
        self.exit_prog_btn.setText(_translate("MainWindow", "Exit"))
